services:
    zikula_users_module.internal.authentication_method_collector:
        class: Zikula\UsersModule\Collector\AuthenticationMethodCollector
        arguments: ["@zikula_extensions_module.api.variable"]

    zikula_users_module.form.default_registration_type:
        class: Zikula\UsersModule\Form\Type\RegistrationType\DefaultRegistrationType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type, alias: "Zikula\\UsersModule\\Form\\Type\\RegistrationType\\DefaultRegistrationType" }

    zikula_users_module.form.default_login_type:
        class: Zikula\UsersModule\Form\Type\DefaultLoginType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type, alias: "Zikula\\UsersModule\\Form\\Type\\DefaultLoginType" }
